services:
  # 3. Jenkins (CI/CD 파이프라인)
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: always
    user: root # [필수] 도커 소켓 접근 권한을 위해 루트로 실행 (간편 설정)
    volumes:
      - ./jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock # [핵심] 젠킨스가 호스트 도커를 조종하게 함
      - /usr/bin/docker:/usr/bin/docker # 젠킨스 내부에서 도커 명령어 사용
    environment:
      - TZ=Asia/Seoul
    networks:
      - gateway-net
    deploy:
      resources:
        limits:
          memory: 2G # 빌드 시 메모리 폭주 방지

# [네트워크 선언]
networks:
  gateway-net:
    external: true
  infra-net:
    name: infra-net
    driver: bridge
