server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html; # React 파일 있는 곳
        index index.html index.htm;
        try_files $uri $uri/ /index.html; # React 새로고침 에러 방지용 (필수)
    }

    location /src/ {
        alias /usr/share/nginx/html/src/;

        autoindex off;
    }
}
